/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mateyr.gestionempleados.MainView;

import com.mateyr.gestionempleados.Panel.PnlTable;
import com.mateyr.gestionempleados.Panel.PnlTree;
import com.mateyr.gestionempleados.controllers.PnlTableController;
import com.mateyr.gestionempleados.controllers.PnlTreeController;
import com.mateyr.gestionempleados.controllers.frmAppDemoController;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author MateyR
 */
public class frmAppDemo extends javax.swing.JFrame {

         
    private frmAppDemoController appDemoController;

   
    
    
    
    
    /**
     * Creates new form frmAppDemo
     */
    public frmAppDemo() {
        initComponents();
        appDemoController = new frmAppDemoController(this);    
    }

    public JPanel getPnlEmpleadoTable() {
        return pnlEmpleadoTable;
    }

    public JPanel getPnlTreeArea() {
        return pnlTreeArea;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBotton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlTreeArea = new javax.swing.JPanel();
        pnlEmpleadoTable = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBotton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAdd.setBackground(new java.awt.Color(153, 0, 204));
        btnAdd.setText("Add");
        btnBotton.add(btnAdd);

        btnEdit.setBackground(new java.awt.Color(153, 255, 153));
        btnEdit.setText("Edit");
        btnBotton.add(btnEdit);

        btnDelete.setText("Delete");
        btnBotton.add(btnDelete);

        getContentPane().add(btnBotton, java.awt.BorderLayout.PAGE_END);

        pnlTreeArea.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlTreeArea, java.awt.BorderLayout.LINE_START);

        pnlEmpleadoTable.setForeground(new java.awt.Color(255, 0, 0));
        pnlEmpleadoTable.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlEmpleadoTable, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(785, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAppDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAppDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAppDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAppDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAppDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JPanel btnBotton;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel pnlEmpleadoTable;
    private javax.swing.JPanel pnlTreeArea;
    // End of variables declaration//GEN-END:variables
}
