/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mateyr.gestionempleados.MainView;

import com.mateyr.gestionempleados.Panel.PnlTable;
import com.mateyr.gestionempleados.Panel.PnlTree;
import com.mateyr.gestionempleados.controllers.PnlTableController;
import com.mateyr.gestionempleados.controllers.PnlTreeController;

/**
 *
 * @author MateyR
 */
public class frmAppDemo extends javax.swing.JFrame {

    private PnlTable pnlTable;
    private PnlTableController pnlTableController;
    
    private PnlTree pnlTree;
    private PnlTreeController pnlTreeController;
    
    /**
     * Creates new form frmAppDemo
     */
    public frmAppDemo() {
        pnlTable = new PnlTable();
        pnlTableController = new PnlTableController(pnlTable);
        
        pnlTree = new PnlTree();
        pnlTreeController = new PnlTreeController(pnlTree);
        
        initComponents();
        pnlEmpleadoTable.add(pnlTable);
        pnlTreeArea.add(pnlTree);
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlEmpleadoTable = new javax.swing.JPanel();
        pnlTreeArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEmpleadoTable.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(pnlEmpleadoTable);

        pnlTreeArea.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(pnlTreeArea);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(785, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAppDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAppDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAppDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAppDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAppDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlEmpleadoTable;
    private javax.swing.JPanel pnlTreeArea;
    // End of variables declaration//GEN-END:variables
}
