/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mateyr.gestionempleados.Panel;

/**
 *
 * @author MateyR
 */
public class PnlTable extends javax.swing.JPanel {

    /**
     * Creates new form PnlTable
     */
    public PnlTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTable = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlButton = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnlTable.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAdd.setText("Add");
        pnlTable.add(btnAdd);

        btnEdit.setText("Edit");
        pnlTable.add(btnEdit);

        btnDelete.setText("Delete");
        pnlTable.add(btnDelete);

        add(pnlTable, java.awt.BorderLayout.PAGE_END);

        pnlButton.setLayout(new java.awt.BorderLayout());

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblEmpleado);

        pnlButton.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(pnlButton, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable tblEmpleado;
    // End of variables declaration//GEN-END:variables
}
