/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mateyr.gestionempleados.Panel;

import javax.swing.JButton;
import javax.swing.JTree;

/**
 *
 * @author MateyR
 */
public class PnlTree extends javax.swing.JPanel {

    /** Creates new form PnlTree */
    public PnlTree() {
        initComponents();
    }

    public JButton getBtnAddArea() {
        return btnAddArea;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }
    
  
    public JTree getTreeArea() {
        return treeArea;
    }
    
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButton = new javax.swing.JPanel();
        btnAddArea = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        PnlTree = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeArea = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        pnlButton.setBackground(new java.awt.Color(153, 0, 0));
        pnlButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnAddArea.setText("Add Area");
        pnlButton.add(btnAddArea);

        btnDelete.setText("Delete");
        pnlButton.add(btnDelete);

        add(pnlButton, java.awt.BorderLayout.PAGE_START);

        PnlTree.setLayout(new java.awt.BorderLayout());

        treeArea.setBackground(new java.awt.Color(0, 0, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeArea.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(treeArea);

        PnlTree.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(PnlTree, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlTree;
    private javax.swing.JButton btnAddArea;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JTree treeArea;
    // End of variables declaration//GEN-END:variables

}
